// §6.2: generate, never send. This module contains no call to either of
// Gmail's outbound-send endpoints (the plain-message send call, or the
// send-a-draft call) — see test/no-send-endpoint.spec.js, which greps all
// of src/ for those literal call patterns and fails the build if either
// appears anywhere, including in a comment like this one (hence the
// deliberately non-literal phrasing above). The gmail.compose scope
// technically permits sending as well as draft management, so this
// boundary is enforced here in code, not assumed from the OAuth scope.

const DRAFT_SUBJECT_PREFIX = '[OPS-DRAFT — NOT SENT] ';

function accountLabel(task) {
  return task.account_name_raw || task.account_id || 'the insured';
}

/** Leads with a recommendation. */
function recommendationVariant(task) {
  return [
    `Hi team — following up on ${accountLabel(task)}.`,
    '',
    `Recommendation: ${task.obligation}`,
    task.due_date ? `This is due ${task.due_date}; flagging now so there's time to act.` : 'No hard deadline was stated — flagging so it does not fall through the cracks.',
    '',
    '(Draft generated by the Ops Event Extractor. A licensed human must review before sending. See docs/SPEC.md §0.7.)'
  ].join('\n');
}

/** Presents options neutrally, no recommendation. */
function neutralVariant(task) {
  return [
    `Hi team — a note on ${accountLabel(task)}.`,
    '',
    `Obligation: ${task.obligation}`,
    task.due_date ? `Stated/derived due date: ${task.due_date}.` : 'No date was stated in the source email.',
    'Options: (1) action it now, (2) confirm with the insured first, (3) mark not applicable and dismiss.',
    '',
    '(Draft generated by the Ops Event Extractor. A licensed human must review before sending. See docs/SPEC.md §0.7.)'
  ].join('\n');
}

export function generateNudgeDrafts(task) {
  return {
    subject: `${DRAFT_SUBJECT_PREFIX}${task.kind}: ${accountLabel(task)}`,
    recommendation: recommendationVariant(task),
    neutral: neutralVariant(task)
  };
}

/**
 * §0.1/§6.2: never sends. In `--live` mode with a Gmail client configured,
 * this would call `gmail.users.drafts.create` (create-only, never
 * `drafts.send`) — no live Gmail OAuth is configured in this environment
 * (ADR 0003), so this always takes the dry-run branch here.
 */
export async function writeDraft(task, { live = false, gmailClient = null } = {}) {
  const drafts = generateNudgeDrafts(task);
  if (!live || !gmailClient) {
    // eslint-disable-next-line no-console
    console.log(`[gmail:dry-run] would create draft "${drafts.subject}"`);
    return { ok: true, dryRun: true, drafts };
  }
  const created = await gmailClient.users.drafts.create({
    userId: 'me',
    requestBody: { message: { raw: Buffer.from(`Subject: ${drafts.subject}\r\n\r\n${drafts.recommendation}`).toString('base64url') } }
  });
  return { ok: true, dryRun: false, draftId: created.data.id, drafts };
}
